on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gopicontainerregistery.azurecr.io
        username: ${{ secrets.acr_gopicontainerregistery_username }}
        password: ${{ secrets.acr_gopicontainerregistery_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/SampleWebApp" -f  "SampleWebApp/Dockerfile" -t gopicontainerregistery.azurecr.io/mykubernate:${{ github.sha }} --label dockerfile-path=SampleWebApp/Dockerfile
        docker push gopicontainerregistery.azurecr.io/mykubernate:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mykubernate_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mykubernateba26 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mykubernateba26`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mykubernateba26
        container-registry-url: gopicontainerregistery.azurecr.io
        container-registry-username: ${{ secrets.acr_gopicontainerregistery_username }}
        container-registry-password: ${{ secrets.acr_gopicontainerregistery_password }}
        secret-name: mykubernatedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mykubernateba26
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          gopicontainerregistery.azurecr.io/mykubernate:${{ github.sha }}
        imagepullsecrets: |
          mykubernatedockerauth
